name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Сборка и установка зависимостей
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    name: Запуск тестов
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Запуск тестов pytest
        run: pytest tests/

  deploy:
    name: Псевдо-деплой на staging
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Псевдо-деплой
        run: |
          echo "Деплой на staging-сервер запущен..."
          echo "Деплой завершён успешно!"
